import Link from "next/link";
import { cn } from "@/lib/utils";
import { Tag } from "./tag";
import Image from "next/image";
import {
  Card,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";

interface PostItemProps {
  slug: string;
  title: string;
  description?: string;
  date: string;
  tags?: Array<string>;
  banner?: string;
}

export function PostItem({
  slug,
  banner,
  title,
  description,
  date,
  tags,
}: PostItemProps) {
  const isNew =
    new Date(date) > new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  return (
    <>
      <Card className="flex relative h-40 justify-between bg-foreground/20 saturate-150 filter backdrop-blur-md">
        <style>
          {`
        @media (min-width: 768px) {
        .article-image {
          clip-path: polygon(0 0, 100% 0, 100% 100%, 20% 100%);
          /* -webkit-mask-image: linear-gradient(to left, black, transparent),
            radial-gradient(at 0 0, black, transparent); */
        }
        }
        `}
        </style>
        <div className="flex justify-between flex-col w-full md:w-[80%] ">
          <CardHeader className="flex flex-col">
            <div className="">
              <Link href={"/" + slug}>
                <CardTitle className=" hover:underline font-bold line-clamp-1 ">
                  {title}
                </CardTitle>
              </Link>
            </div>

            <CardDescription className="line-clamp-2 text-xs font-light">
              {description?.toString()} Lorem ipsum dolor sit, amet consectetur
              adipisicing elit. In consequuntur, accusantium rem ad dicta
              similique accusamus et, deserunt excepturi obcaecati labore ex
              soluta! Minus ad assumenda unde eum, quia reiciendis. Enim quidem
              esse officiis facilis rem cumque quis, unde, tempore excepturi
              vero nobis adipisci odit earum placeat hic velit corrupti commodi
              cum exercitationem doloribus fugit repudiandae, nesciunt ducimus!
              Provident, fugiat?
            </CardDescription>
          </CardHeader>
          <CardFooter className="absolute bottom-0 w-full md:w-[80%]">
            <div className="w-full flex justify-between">
              <div className="flex gap-2">
                {tags?.map((tag) => <Tag tag={tag} key={tag} />)}
              </div>
              <div className="md:hidden block text-nowrap">
                <Link href={"/" + slug}>→</Link>
              </div>
            </div>
          </CardFooter>
        </div>
        <Link
          href={"/" + slug}
          className={cn(
            buttonVariants({ variant: "default" }),
            "absolute bottom-0 right-0 py-0 m-2 text-xs hidden md:flex"
          )}
        >
          Open →
        </Link>
        {isNew && (
          <Badge className="absolute right-0 w-fit h-fit m-2 animate-pulse">
            NEW
          </Badge>
        )}
        {banner && (
          <Image
            height={200}
            width={400}
            alt="Banner for article generated by midjourney"
            loading="lazy"
            className="article-image object-cover absolute w-full -z-10 opacity-15 md:opacity-100 md:w-52 right-0 z-1 rounded-r image-overlay transition-all h-full"
            src={banner}
          />
        )}
      </Card>
    </>
  );
}

{
  /* <div className="">
<dl>
  <dt className="sr-only">Published On</dt>
  <dd className="text-sm sm:text-base font-medium flex items-center gap-1">
    <Calendar className="h-4 w-4" />
    <time dateTime={date}>{formatDate(date)}</time>
  </dd>
</dl>
<Link
  href={"/" + slug}
  className={cn(buttonVariants({ variant: "link" }), "py-0")}
>
  Read more →
</Link>
</div> */
}
