import { type SiteTypes } from '@/types';

import { env } from '@/env.mjs';

export const siteConfig: SiteTypes = {
  name: 'AE1 PORTFOLIO',
  author: 'THEALIFHAKER1',
  description:
    'This is my personal portfolio website to showcase my projects and skills. Built with Next.js, React, Tailwind CSS, Radix UI, and shadcn/ui.',
  keywords: [
    'Next.js',
    'React',
    'Tailwind CSS',
    'Radix UI',
    'shadcn/ui',
    'Portfolio',
    'AE1',
    'THEALIFHAKER1',
    'Developer',
    'Designer',
    'Frontend',
    'Fullstack',
    'Web Developer',
    'Web Designer',
    'Software Engineer',
    'UI/UX Engineer',
    'UI/UX Designer',
    'Backend Developer',
    'Backend Engineer',
    'MERN Stack',
    'JAM Stack',
    'PWA',
    'SPA',
    'SSR',
    'SEO',
    'SEO Friendly',
    'Responsive',
    'Mobile First',
    'Dark Mode',
    'Light Mode',
    'PWA',
    'SPA',
    'SSR',
    'SEO',
    'SEO Friendly',
    'Responsive',
    'Mobile First',
    'Dark Mode',
    'Light Mode',
  ],
  url: {
    base: env.NEXT_PUBLIC_APP_URL,
    author: 'https://ae1.tech',
  },
  links: {
    github: 'https://github.com/THEALIFHAKER1/AE1-PORTFOLIO',
  },
  ogImage: `${env.NEXT_PUBLIC_APP_URL}/api/og`,
};
